{"uuid": "cf47ea9f-960e-462f-8c20-46ac0e330bf1", "children": ["34c16849-a6c9-40af-a91f-9007deed5a19"], "befores": [{"name": "base_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.70)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7BF432775+28773]\n\t(No symbol) [0x00007FF7BF39AFB0]\n\t(No symbol) [0x00007FF7BF23552A]\n\t(No symbol) [0x00007FF7BF20F2B5]\n\t(No symbol) [0x00007FF7BF2B5FD7]\n\t(No symbol) [0x00007FF7BF2CEA92]\n\t(No symbol) [0x00007FF7BF2AED43]\n\t(No symbol) [0x00007FF7BF27A548]\n\t(No symbol) [0x00007FF7BF27B6B1]\n\tGetHandleVerifier [0x00007FF7BF75F45D+3358029]\n\tGetHandleVerifier [0x00007FF7BF77430D+3443709]\n\tGetHandleVerifier [0x00007FF7BF7683FD+3394797]\n\tGetHandleVerifier [0x00007FF7BF4F929B+842635]\n\t(No symbol) [0x00007FF7BF3A654F]\n\t(No symbol) [0x00007FF7BF3A1FA4]\n\t(No symbol) [0x00007FF7BF3A213D]\n\t(No symbol) [0x00007FF7BF391629]\n\tBaseThreadInitThunk [0x00007FFF6D927374+20]\n\tRtlUserThreadStart [0x00007FFF6DCBCC91+33]\n\n", "trace": "  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\_pytest\\fixtures.py\", line 897, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\Desktop\\Python\\Тест для работы\\--chekoev_tz-main\\--chekoev_tz-main\\tests\\ui\\conftest.py\", line 10, in base_page\n    return BasePage(SetupDriver.setup_driver())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\Desktop\\Python\\Тест для работы\\--chekoev_tz-main\\--chekoev_tz-main\\src\\ui\\page_and_helpers\\base_page.py\", line 26, in __init__\n    self.open_main_page()\n  File \"C:\\Users\\Vlad\\Desktop\\Python\\Тест для работы\\--chekoev_tz-main\\--chekoev_tz-main\\src\\ui\\page_and_helpers\\base_page.py\", line 52, in open_main_page\n    assert self.element_is_present(locator=CustomBasePageLocators.CATEGORY_CARD_BY_NAME.format(\"Телевизоры\"))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\Desktop\\Python\\Тест для работы\\--chekoev_tz-main\\--chekoev_tz-main\\src\\ui\\page_and_helpers\\base_page.py\", line 98, in element_is_present\n    self.wait.until(EC.visibility_of_element_located(locator=(By.XPATH, locator)))\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 156, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Vlad\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1731925916838, "stop": 1731925919883}], "start": 1731925916838, "stop": 1731925922144}